ansible_user: 'mimmo_ansible'
ansible_password: 'MimmoAnsible.123'
ansible_port: 5986
ansible_connection: winrm
# The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore
